server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://gcp.connect.psdb.cloud:3306/toy_pj?sslMode=VERIFY_IDENTITY&enabledSslProtocolSuites=TLSv1.2
    username: 5xa59bkrvomdffojh03u
    password: pscale_pw_E2BTPvYwYznxKOZRuE3H9rP728DFZUFEs0DKMWGV0KI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none    # PlanetScale은 DDL 변경 금지라 update/create 안 됨!
    show-sql: true
    properties:
      hibernate:
        format_sql: true
